# Generated by Django 4.0.4 on 2022-05-17 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('is_active', models.BooleanField(default=True, verbose_name='State')),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name Genres')),
                ('url', models.URLField(verbose_name='Url Genres')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date Update')),
                ('is_active', models.BooleanField(default=True, verbose_name='State')),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code Unique Generate')),
                ('artistName', models.CharField(max_length=255, verbose_name='Artist Name')),
                ('name', models.CharField(max_length=255, verbose_name='Name Track')),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id Track')),
                ('releaseDate', models.DateField(verbose_name='Release Date')),
                ('kind', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kind Name')),
                ('artistId', models.PositiveIntegerField(unique=True, verbose_name='Artist Date')),
                ('artistUrl', models.URLField(verbose_name='url Artist')),
                ('contentAdvisoryRating', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content Advisors')),
                ('artworkUrl100', models.URLField(verbose_name='Url Arts')),
                ('url', models.URLField(verbose_name='url Track')),
                ('genres', models.ManyToManyField(to='tracks.genres')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'abstract': False,
            },
        ),
    ]
